# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99cd8bf8af37e324b874590ec0eca8680b3cec033a3e1c934475168a9d968a13f8c62d85b00925f68b9170b59c6b8b313b8cd9ef5f453160af6a2ea553d1fb5e

test:
  secret_key_base: c0d0649034940b9b8baea06878e58b000865fc855a8fc747a9e4cb197237ac7b7014dbce53818ef3e21066c697fe8a3d315b482b10cdc5dee08a082cd05e9ab7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
